apiVersion: kyklos.kyklos.io/v1alpha1
kind: TimeWindowScaler
metadata:
  name: nginx-test-scaler
  namespace: kyklos-demo
spec:
  # Reference to the target Deployment to scale
  targetRef:
    name: nginx-test

  # Timezone for interpreting window times (IANA timezone)
  timezone: "UTC"

  # Default number of replicas when no windows match
  defaultReplicas: 2

  # Grace period in seconds for scale-down operations (optional)
  gracePeriodSeconds: 60

  # Time windows for scaling
  windows:
    # Morning peak - should be active now (10:00-11:00 UTC)
    - name: "morning-peak"
      start: "10:00"
      end: "11:00"
      replicas: 5

    # Afternoon peak - will be active later (14:00-16:00 UTC)
    - name: "afternoon-peak"
      start: "14:00"
      end: "16:00"
      replicas: 3
